<!-- footer -->
<div class="why-us-footer-block">
    <div class="content">
        <div class="row-new">
            <div class="column-new-add" >
                <h2>Why Gemsclip?</h2>
                <ul>
                    <li>Fair Price - We offer high quality work along with excellent support and customer service at a fair and reasonable price. We do our best to make sure you stay in budget and still get a great result.</li>
                    <li>Sales Channel - Online Platform (Gemsclip.com) & dedicated Key Account Managers</li>
                    <li>Post-sales Service - Acquiring Client Feedback. After-sales service for IT & electronic products & along with</li>
                    <li>Procurement - Sourcing products from one of our 1000+ merchants or from warehouse</li>
                </ul>

                <h2>A One Stop Shop</h2>
                <ul>
                    <li>Users can navigate seamlessly through our site and acquire information about any product they are looking for</li>
                    <li>Our e-commerce platform offers buyers with a wide selection of products to choose from along with a hassle-free buying experience.</li>
                    <li>You will find all your desired items with negotiable rate throughout gemsclip.com</li>

                </ul>
            </div>
            <div class="column-new-add">
                <h2>Simplifying Online Procurement and Supplies</h2>
                <ul>
                    <li>We are providing such a platform from where you can easily order your products within some click</li>
                    <li>Throughout your entire history you can take any decision of procurement of your company</li>
                    <li>Manage your multiple delivery locations from online platform even your products too.</li>

                </ul>

                <h2>Choose What Suits Best for you!</h2>
                <ul>
                    <li>Pick up everything suitable what you need best for your organization.</li>
                    <li>Minimize your cost of purchase by choosing our services and rest assured.</li>
                    <li>Compare our services to others to analyze what youre being benefited.</li>
                    <li>Payment - We receive Bank Accounts Transfer, electronic payments in different modes as well as offer the facility of cash on delivery (COD) to facilitate secure transactions.</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="footer-list-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item active">About us</li>
                    <li class="list-group-item"><a href="about-gemsclip">About Gemsclip</a></li>
                    <li class="list-group-item"><a href="gemsclip-team">Gemsclip Team</a></li>
                    <li class="list-group-item"><a href="career">Career</a></li>
                    <li class="list-group-item"><a href="contact">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item active"><a href="support">Support</a></li>
                    <li class="list-group-item"><a href="return-policy">Return Policy</a></li>
                    <li class="list-group-item"><a href="credit-policy">Credit Policy</a></li>
                    <li class="list-group-item"><a href="terms-conditions">Terms & Conditions</a></li>
                    <li class="list-group-item"><a href="privacy-policy">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item active">MEDIA</li>
                    <li class="list-group-item"><a href="news">News</a></li>
                    <li class="list-group-item"><a href="publications">Publications</a></li>
                    <li class="list-group-item active">Join Us On</li>
                    <li class="list-group-item">
                        <a href="#"><img   src="<?=$block->getViewFileUrl("images/media/fb-icon.png");?>"  alt="Facebook"></a>
                        <a href="#"><img  src="<?=$block->getViewFileUrl("images/media/twitter-icon.png");?>"  alt="twitter"></a>
                        <a href="#"><img   src="<?=$block->getViewFileUrl("images/media/linkedin-icon.png");?>"  alt="linkedin"></a>
                    </li>
                </ul>
            </div>
        </div>
        <hr class="featurette-divider">
        <p class="copyright">&copy; 2019 Gemsclip. All Rights Reserved.</p>
    </div>
</div>
<!--.footer-->
