<style>


* {
  box-sizing: border-box;

}

.column-new-add {
  float: left;
  width: 50%;
  padding: 10px;
  height: 550px; /* Should be removed. Only for demonstration */
}

/* Clear floats after the columns */
.row-new:after {
    background-image: none !important;
  content: "";
  display: table;
  clear: both;

}

</style>
<div class="row-new">
  <div class="column-new-add" >
    <h2>Why Gemsclip?</h2>
     <ul>
        <li>Fair Price - We offer high quality work along with excellent support and customer service at a fair and reasonable price. We do our best to make sure you stay in budget and still get a great result.</li>
        <li>Sales Channel - Online Platform (Gemsclip.com) & dedicated Key Account Managers</li>
        <li>Post-sales Service - Acquiring Client Feedback. After-sales service for IT & electronic products & along with</li>
        <li>Procurement - Sourcing products from one of our 1000+ merchants or from warehouse</li>
    </ul>

    <h2>A One Stop Shop</h2>
     <ul>
        <li>Users can navigate seamlessly through our site and acquire information about any product they are looking for</li>
        <li>Our e-commerce platform offers buyers with a wide selection of products to choose from along with a hassle-free buying experience.</li>
        <li>You will find all your desired items with negotiable rate throughout gemsclip.com</li>

    </ul>
  </div>
  <div class="column-new-add">
    <h2>Simplifying Online Procurement and Supplies</h2>
     <ul>
        <li>We are providing such a platform from where you can easily order your products within some click</li>
        <li>Throughout your entire history you can take any decision of procurement of your company</li>
        <li>Manage your multiple delivery locations from online platform even your products too.</li>

    </ul>

    <h2>Choose What Suits Best for you!</h2>
     <ul>
        <li>Pick up everything suitable what you need best for your organization.</li>
        <li>Minimize your cost of purchase by choosing our services and rest assured.</li>
        <li>Compare our services to others to analyze what youre being benefited.</li>
        <li>Payment - We receive Bank Accounts Transfer, electronic payments in different modes as well as offer the facility of cash on delivery (COD) to facilitate secure transactions.</li>
    </ul>
  </div>
</div>